// test-apps/vue-test-app/src/App.vue
<script setup lang="ts">

import { staticAssets, type FilesInFolder, type StaticAssetPath} from "virtual:static-assets"

type  Icons = FilesInFolder<'icons/sun/'>;

type Suns = {
  icon: Icons,
  name: string
}
const assetPath: StaticAssetPath = 'icons/sun/line-md--sunny.svg';

const suns: Suns[] = [
  {
    icon: "icons/sun/line-md--sunny.svg",
    name: "Sunny"
  },
  {
    icon: "icons/sun/line-md--sun-rising-loop.svg",
    name: "Sun Rising"
  },
  {
    icon: "icons/sun/line-md--sun-rising-twotone-loop.svg",
    name: "Sun Rising Twotone"
  },
  {
    icon: "icons/sun/line-md--sun-rising-filled-loop.svg",
    name: "Sun Rising Filled"
  }

]

</script>

<template>
  <div>
    <img :src="staticAssets('logo.png')" class="logo" alt="Vite Static Assets logo" />
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <h1>Vite + <span style="color: lightblue;">vite-static-assets-plugin</span> + Vue</h1>
  
  <div class="suns-list">
    <div v-for="(sun, index) in suns" :key="index" class="sun-item">
      <img :src="sun.icon" :alt="sun.name" class="sun-icon" />
      <span>{{ sun.name }}</span>
    </div>
  </div>
  <img :src="staticAssets(assetPath)" class="logo" alt="logo" />
   
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// test-apps/react-test-app/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import { type StaticAssetPath, staticAssets , type FilesInFolder} from "virtual:static-assets"

type  Icons = FilesInFolder<'icons/sun/'>;

type Suns = {
  icon: Icons,
  name: string

}
const suns: Suns[] = [
  {
    icon: "icons/sun/line-md--sunny.svg",
    name: "Sunny"
  },
  {
    icon: "icons/sun/line-md--sun-rising-loop.svg",
    name: "Sun Rising"
  },
  {
    icon: "icons/sun/line-md--sun-rising-twotone-loop.svg",
    name: "Sun Rising Twotone"
  },
  {
    icon: "icons/sun/line-md--sun-rising-filled-loop.svg",
    name: "Sun Rising Filled"
  }

]
// Type-safe variables
const assetPath: StaticAssetPath = 'icons/sun/line-md--sunny.svg';


function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank" rel="noreferrer">
          <img src={staticAssets("logo.png")} className="logo" alt="Vite Static Assets logo" />
        </a>

        <a href="https://vite.dev" target="_blank" rel="noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
     {suns.map(sun => (
        <img key={sun.name} src={staticAssets(sun.icon)} className="logo" alt={sun.name} style={{
          width: "24px"
        }} />
      ))}
      <h1>Vite + <span style={{
        color: "lightblue"
      }}>vite-static-assets-plugin</span> + React</h1>
      <div className="card">
        <button
          type="button"
        onClick={() => setCount((count: number) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
      <img src={staticAssets(assetPath)} className="logo" alt="logo" />
    </>
  )
}

export default App
